name: Pull Request

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read
  packages: read

jobs:
  pull_request:
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
