name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  ci:
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
    with:
      audit-script: npm run audit
      output-test-results: true
      test-script: npm run test:ci

  publish:
    needs: ci
    uses: makerxstudio/shared-config/.github/workflows/node-trusted-publish.yml@main
    with:
      access: public
      tag: beta
