name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    name: Release package to NPM
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Use Node.js latest LTS version
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          # == Cache frequently built and/or with large dependencies ==
          # == Eviction policy: not accessed in over 7 days
          # == Limit: 10 GB
          # cache: 'npm'
          # == Path to lock file when using mono repos ==
          # cache-dependency-path: subdir/package-lock.json

      - name: Restore packages
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build package
        run: npm run build

      - name: Run tests
        run: npm test


      - name: Publish (if version has been updated)
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: 'package.json'
          check-version: true
          registry: "https://npm.pkg.github.com"

